Rails.application.routes.draw do
  get 'example/goalimage' => 'example#goalimage'
  get 'example/recordimage' => 'example#recordimage'
  get 'example/checkimage' => 'example#checkimage'
  get 'example/useiamge' => 'example#useimage'
  get 'example/exaBack' => 'example#exaBack'

  get 'check/checklist' => 'check#checklist'
  get 'check/checkpass' => 'check#checkpass'
  get 'check/checkinfo' => 'check#checkinfo'
  get 'check/checkprogress' => 'check#checkprogress'
  get 'check/progresscontent' => 'check#progresscontent'
  get 'check/displaycontent' => 'check#displaycontent'
  get 'check/judger' => 'check#judger'
  get 'check/stampsheet0' => 'check#stampsheet0'
  get 'check/stampsheet1' => 'check#stampsheet1'
  get 'check/stampsheet2' => 'check#stampsheet2'
  get 'check/stampsheet3' => 'check#stampsheet3'
  get 'check/stampsheet4' => 'check#stampsheet4'
  get 'check/stampsheet5' => 'check#stampsheet5'
  get 'check/stampsheet6' => 'check#stampsheet6'
  get 'check/stampsheet7' => 'check#stampsheet7'
  get 'check/errorsheet' => 'check#errorsheet'
  get 'check/gohome' => 'check#gohome'

  get 'records/recordimage1' => 'records#recordimage1'
  get 'records/recordimage2' => 'records#recordimage2'
  get 'records/recordimage3' => 'records#recordimage3'
  get 'records/recordimage4' => 'records#recordimage4'
  get 'records/recordimage5' => 'records#recordimage5'
  get 'records/recordimage6' => 'records#recordimage6'
  get 'records/recordimage7' => 'records#recordimage7'
  get 'records/recordimage8' => 'records#recordimage8'
  get 'records/recordimage9' => 'records#recordimage9'
  get 'records/recordimage10' => 'records#recordimage10'

  get 'records/select1' => 'records#select1'
  get 'records/select2' => 'records#select2'
  get 'records/select3' => 'records#select3'
  get 'records/select4' => 'records#select4'
  get 'records/select5' => 'records#select5'
  get 'records/select6' => 'records#select6'
  get 'records/select7' => 'records#select7'
  get 'records/select8' => 'records#select8'
  get 'records/select9' => 'records#select9'
  get 'records/select10' => 'records#select10'

  get 'records/recordpage' => 'records#recordpage'
  get 'records/recordwell' => 'records#recordwell'
  get 'records/recordBack' => 'records#recordBack'

  get 'goals/goaldecision' => 'goals#goaldecision'
  get 'goals/goalconfirm' => 'goals#goalconfirm'
  get 'goals/goallist' => 'goals#goallist'
  get 'goals/goalcreate' => 'goals#goalcreate'

  root 'home#start'
  get 'menu' => 'home#menu'
  get 'login' => 'home#login'
  get 'new' => 'home#new'
  get 'top' => 'home#top'

  post 'home/authentication' => 'home#authentication'
  post 'home/create' => 'home#create'
  post 'home/logout' => 'home#logout'
  post 'records/recordcreate' => 'records#recordcreate'
  post 'records/imageRec1' => 'records#imageRec1'
  post 'records/imageRec2' => 'records#imageRec2'
  post 'records/imageRec3' => 'records#imageRec3'
  post 'records/imageRec4' => 'records#imageRec4'
  post 'records/imageRec5' => 'records#imageRec5'
  post 'records/imageRec6' => 'records#imageRec6'
  post 'records/imageRec7' => 'records#imageRec7'
  post 'records/imageRec8' => 'records#imageRec8'
  post 'records/imageRec9' => 'records#imageRec9'
  post 'records/imageRec10' => 'records#imageRec10'

  post 'goals/goalcreate' => 'goals#goalcreate'
  post 'check/checkauthentication' => 'check#checkauthentication'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
